#!/bin/sh

set -eu

# run on upgrade and new package installation
if [ "$1" = "configure" ]; then

  # create user 
  if ! getent passwd dtdnssync >/dev/null; then
    adduser --system --group --quiet --no-create-home --home /nonexistent dtdnssync
  fi
  
  # set cfg file ownership
  chown root:dtdnssync /etc/dtdnssync/
  chown root:dtdnssync /etc/dtdnssync/dtdnssync.cfg
  chmod 0640 /etc/dtdnssync/dtdnssync.cfg
  
  # setup logfile
  if [ ! -e /var/log/dtdnssyncd.log ]
  then
    install -o dtdnssync -g dtdnssync -m 0640 /dev/null /var/log/dtdnssyncd.log
  fi

fi

#DEBHELPER#
