#!/bin/sh

set -eu

case "$1" in
  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

  purge)
    rm -f /var/log/dtdnssyncd.log
    userdel dtdnssync
    ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
esac

#DEBHELPER#
